Feature/feature
MichaelMal1992/Gallery pull request #1
Opened 2021-08-05 17:39 UTC by MichaelMal1992

2021-08-06 20:57 UTC, mbulatIT requested changes
Структурируй файлы в проекте по папкам. Отдельно для ViewController'ов, с подпапками для каждого (и добавь в них класс контроллера и все экстеншены к нему), отдельно для вспомогательных файлов типа ап и сцен делегата, отдельно для менеджеров и тд

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+ImagePicker.swift
> +    func getImagesStringArray() -> [String] {
Эта функция должна быть в менеджере. Иначе зачем тебе менеджер, если ты все равно напрямую работаешь с FileManager'ом

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+ImagePicker.swift
> +        if Manager.shared.fileManager.fileExists(atPath: Manager.shared.imagesFolderURL.path) {
Эта функция должна быть в менеджере. Иначе зачем тебе менеджер, если ты все равно напрямую работаешь с FileManager'ом

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+ImagePicker.swift
> +        if Manager.shared.fileManager.fileExists(atPath: Manager.shared.imagesFolderURL.path) {
Эта функция должна быть в менеджере. Иначе зачем тебе менеджер, если ты все равно напрямую работаешь с FileManager'ом

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+ImagePicker.swift
> +        if Manager.shared.fileManager.fileExists(atPath: Manager.shared.imagesFolderURL.path) {
Эта функция должна быть в менеджере. Иначе зачем тебе менеджер, если ты все равно напрямую работаешь с FileManager'ом

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+ImagePicker.swift
> +    func removeImageFromIndex(index: Int) {
Эта функция должна быть в менеджере. Иначе зачем тебе менеджер, если ты все равно напрямую работаешь с FileManager'ом

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+ImagePicker.swift
> +        guard let image = image else {
Эта функция должна быть в менеджере. Иначе зачем тебе менеджер, если ты все равно напрямую работаешь с FileManager'ом

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TableView.swift
> +    func numberOfSections(in tableView: UITableView) -> Int {
Эту функцию можно не писать, по умолчанию кол-во секций -- 1. А если понадобится потом, то она относится к Datasource, а не к Delegate

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TableView.swift
> +                for array in Manager.shared.imagesArray {
array в переводе с англ. -- массив. У тебя получается что ты перебираешь массивы, в массиве картинок, а надо перебирать картинки в массиве картинок

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TableView.swift
> +                    guard let currentName = Manager.shared.currentImageName else { return 0 }
лучше хранить не текущее имя картинки, а текущий индекс, тогда не нужно будет перебирать все значения, а можно будет обращаться напрямую по индексу. И хранить этот индекс/имя должен не менеджер, а контроллер, в котором эти картинки отображаются

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TableView.swift
> +                return cell
этот else лишний, код и так пойдет дальше и в 56 строке вернет cell

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TextField.swift
> +    func saveComents(_ textField: UITextField) {
По сути это функция добавления, а не сохранения коммента. И коммент добавляется один, поэтому должен быть в единственном числе

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TextField.swift
> +                    createAlertCancel(title: "The gallery is empty")
не нужно показывать Алерт если коммент пустой, просто дизейбли кнопку добавления коммента

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TextField.swift
> +                createAlertCancel(title: "A comment cannot be only from a spaces")
то же самое

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+TextField.swift
> +            createAlertCancel(title: "A comment cannot be empty")
то же самое. Вообще лучше вынести функционал валидация коммента в отдельную функцию

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+UICollectionViewDataSource.swift
> +        guard let array = getArrayImages() else {
Используй значение по умолчанию для разворачивания опционала здесь

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+UICollectionViewDataSource.swift
> +
лишняя пустая строка

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/GalleryViewController+UICollectionViewDataSource.swift
> +        if Manager.shared.selectedIndexPath == nil {
почему бы просто не вернуть 0?

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/SettingsViewController+TextField.swift
> +                    createAlertCancel(title: "The new password cannot contain a spaces")
Добавить локализации везде, где используется текст

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/SettingsViewController+TextField.swift
> +        let repeatPassword = repeatNewPasswordTextField.text
вынеси в отдельную функцию, очень громоздко и сложно воспринимать

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+Alert.swift
> +    func createAlertWithPassword(title: String, password: String, completion: @escaping () -> ()) {
Эта функция относится только к контроллеру авторизации, не нужно ее добавлять во все контроллеры

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+Alert.swift
> +    func createAlertWithNewPassword(title: String, completion: @escaping () -> ()) {
В авторизацию и название не соответствует работе функции

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+Alert.swift
> +    func createAlertRepeatNewPassword(title: String, completion: @escaping () -> ()) {
В авторизацию и название не соответствует работе функции

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+Codable.swift
> +extension UIViewController {
Это работа менеджера, перенеси туда

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+Date.swift
> +    func getCurrentDate() -> String {
добавь в название String, чтоб было понятно что возвращается строка из даты

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+GetImagesArray.swift
> +    func getArrayImages() -> [UIImage]? {
Это точно не нужно во всех контроллерах

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+GetImagesArray.swift
> +            return nil
вместо nil можно возвращать пустой массив, не придется работать с опционалами

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+NewViewController.swift
> +    func createNewViewController(_ identifier: String) {
название

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+NewViewController.swift
> +        navigationController?.pushViewController(newViewController, animated: true)
должен быть выбор, как показывать контроллер

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+UserDefaults.swift
> +    func setDataValue(_ data: Data) {
Совсем не понятно что за data и куда сетается. Если хочешь убрать обращения к userDefaults из контроллеров, можеть создать UserDefaultsManager

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Extension/UIViewController+UserDefaults.swift
> +    func getDataValue() -> Data {
то же самое

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/GalleryViewController.swift
> +    @IBOutlet weak var imagesCollectionView: UICollectionView!
сделай атлеты приватными

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/GalleryViewController.swift
> +    private func likeImageViewDidPressed() {
название не соотносится с содержимым. Функция явно для настройки вьюхи, используй что-то вроде setupLikeTappableImageView

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/GalleryViewController.swift
> +    private func comentImageViewDidPressed() {
название не соотносится с содержимым

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/GalleryViewController.swift
> +    private func trashImageViewDidPressed() {
название не соотносится с содержимым

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/GalleryViewController.swift
> +    private func addImageViewDidPressed() {
название не соотносится с содержимым

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/GalleryViewController.swift
> +    func setupLikeImageView() {
название не соотносится с содержимым. Тут уместнее Update

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Image.swift
> +class Image: Codable {
для свойств Coddable класса не нужны значения по умолчанию

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Image.swift
> +class Comment: Codable {
Класс Comment должен содержать информацию только об одном комменте

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Image.swift
> +    var comments = Comment()
Тут должен быть массив комментов

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/ImagesCollectionViewCell.swift
> +    override func awakeFromNib() {
удалить если не используется

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Manager.swift
> +class Manager {
Менеджер должен упрощать работу с каким-то конкретным функционалом. Название должно отображать то, для чего предназначен менеджер

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Manager.swift
> +    var keyForImage = "User_Image_Class"
слово ключ лучше использовать в конце. imageKey

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/PasswordManager.swift
> +
если делаешь менеджер, то все что касается создания, изменения, удаления должно находиться здесь

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
Удалить неиспользуемые функции

2021-08-06 20:57 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/TappableImageView.swift
> +    @objc func handleTapForLikeImageView(_ sender: UITapGestureRecognizer) {
для такого кол-ва хендлеров лучше создать делегат, с соответствующими методами

2021-08-07 08:10 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Assets.xcassets/pictureFive_icon.imageset/Contents.json
> +{
удалил ненужные

2021-08-07 09:33 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/AuthorizationViewController.swift
> +    override func viewDidAppear(_ animated: Bool) {
удалил

2021-08-07 09:35 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/CommentsTableViewCell.swift
> +    override func awakeFromNib() {
удалил

2021-08-07 09:43 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/Manager.swift
> +    var keyForImage = "User_Image_Class"
исправил

2021-08-07 09:48 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
удалил

2021-08-07 10:14 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/AuthorizationViewController.swift
> +            PasswordManager.shared.password = password
исправил

2021-08-08 11:31 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/AuthorizationViewController.swift
> +            createAlertWithNewPassword(title: "Create a password and don't share it with others") {
добавил

2021-08-08 20:49 UTC, mbulatIT requested changes

2021-08-08 20:49 UTC, mbulatIT commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/AuthorizationViewController.swift
> +        if let password = UserDefaults.standard.value(forKey: PasswordManager.shared.keyToPassword) as? String {
Обращайся к менеджеру для проверки пароля, пусть он сам в юзер дефолтс ходит

2021-08-08 21:06 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/AuthorizationViewController.swift
> +        if let password = UserDefaults.standard.value(forKey: PasswordManager.shared.keyToPassword) as? String {
Исправил. Пароли хранятся в кийчейне. За реализацию отвечает отдельный менеджер(первая авторизация, проверка, сохранение и удаление)

2021-08-08 23:22 UTC, MichaelMal1992 commented on Gallery/StoragePicturesWithPasswordApp/StoragePicturesWithPasswordApp/PasswordManager.swift
> +
исправил

2021-08-19 14:00 UTC, merged